/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import app.Main;


public class MainASYS extends javax.swing.JFrame {
    Main main;
    public MainASYS(Main main) {
        initComponents();
        this.main = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        ProgramacionLineal = new javax.swing.JLabel();
        MetodoTransporte = new javax.swing.JLabel();
        logoTecNM = new javax.swing.JLabel();
        lbASYSC = new javax.swing.JLabel();
        bgLogo = new javax.swing.JLabel();
        lblTema2 = new javax.swing.JLabel();
        lblTema1 = new javax.swing.JLabel();
        lblTema3 = new javax.swing.JLabel();
        TeoriaInventarios = new javax.swing.JLabel();
        lblFoot1 = new javax.swing.JLabel();
        lblFoot = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(204, 204, 255));
        bg.setForeground(new java.awt.Color(204, 204, 204));
        bg.setPreferredSize(new java.awt.Dimension(800, 500));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProgramacionLineal.setBackground(new java.awt.Color(0, 0, 0));
        ProgramacionLineal.setForeground(new java.awt.Color(153, 255, 153));
        ProgramacionLineal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coorr.png"))); // NOI18N
        ProgramacionLineal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProgramacionLineal.setOpaque(true);
        ProgramacionLineal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProgramacionLinealMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProgramacionLinealMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProgramacionLinealMouseExited(evt);
            }
        });
        bg.add(ProgramacionLineal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 120, 110));

        MetodoTransporte.setBackground(new java.awt.Color(0, 0, 0));
        MetodoTransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/transporte.png"))); // NOI18N
        MetodoTransporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MetodoTransporte.setOpaque(true);
        MetodoTransporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MetodoTransporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MetodoTransporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MetodoTransporteMouseExited(evt);
            }
        });
        bg.add(MetodoTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 120, -1));

        logoTecNM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo itess-blanco new-small.png"))); // NOI18N
        bg.add(logoTecNM, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 210, 80));

        lbASYSC.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbASYSC.setForeground(new java.awt.Color(51, 51, 255));
        lbASYSC.setText("Portafolio Digital 2023 ITESS-TICS MATERIA");
        lbASYSC.setToolTipText("");
        bg.add(lbASYSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 500, 40));

        bgLogo.setForeground(new java.awt.Color(204, 204, 255));
        bgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/01.jpg"))); // NOI18N
        bg.add(bgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -280, 470, 790));

        lblTema2.setForeground(new java.awt.Color(0, 153, 153));
        lblTema2.setText("Metodo de Transporte y ");
        bg.add(lblTema2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 140, 20));

        lblTema1.setForeground(new java.awt.Color(0, 153, 153));
        lblTema1.setText("Progromacion Lineal");
        bg.add(lblTema1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 120, -1));

        lblTema3.setForeground(new java.awt.Color(0, 153, 153));
        lblTema3.setText("Teoria de inventarios y");
        bg.add(lblTema3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, -1, -1));

        TeoriaInventarios.setBackground(new java.awt.Color(0, 0, 0));
        TeoriaInventarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alm.png"))); // NOI18N
        TeoriaInventarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TeoriaInventarios.setOpaque(true);
        TeoriaInventarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TeoriaInventariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TeoriaInventariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TeoriaInventariosMouseExited(evt);
            }
        });
        bg.add(TeoriaInventarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 130, 120));

        lblFoot1.setForeground(new java.awt.Color(51, 204, 255));
        lblFoot1.setText("ITESS-TICS-2023 Ago-Dic");
        bg.add(lblFoot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, -1, -1));

        lblFoot.setForeground(new java.awt.Color(51, 153, 255));
        lblFoot.setText("ERICK FLORES TAPIA");
        bg.add(lblFoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Planeacion de Actividades");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Lineas de espera");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 820, 508);
    }// </editor-fold>//GEN-END:initComponents

    private void ProgramacionLinealMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProgramacionLinealMouseEntered
        ProgramacionLineal.setBackground(Color.yellow);
    }//GEN-LAST:event_ProgramacionLinealMouseEntered

    private void ProgramacionLinealMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProgramacionLinealMouseExited
        ProgramacionLineal.setBackground(Color.black);
    }//GEN-LAST:event_ProgramacionLinealMouseExited

    private void MetodoTransporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MetodoTransporteMouseEntered
        MetodoTransporte.setBackground(Color.yellow);
    }//GEN-LAST:event_MetodoTransporteMouseEntered

    private void MetodoTransporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MetodoTransporteMouseExited
        MetodoTransporte.setBackground(Color.black);
    }//GEN-LAST:event_MetodoTransporteMouseExited

    private void ProgramacionLinealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProgramacionLinealMouseClicked
        // TODO add your handling code here:
        main.mainASYS.setVisible(false);
        
        main.programacionLineal = new ProgramacionLineal(this.main);
        main.programacionLineal.setVisible(true);        
    }//GEN-LAST:event_ProgramacionLinealMouseClicked

    private void TeoriaInventariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeoriaInventariosMouseEntered
        // TODO add your handling code here:
        TeoriaInventarios.setBackground(Color.yellow);
    }//GEN-LAST:event_TeoriaInventariosMouseEntered

    private void TeoriaInventariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeoriaInventariosMouseExited
        // TODO add your handling code here:
        TeoriaInventarios.setBackground(Color.black);
    }//GEN-LAST:event_TeoriaInventariosMouseExited

    private void MetodoTransporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MetodoTransporteMouseClicked
        // TODO add your handling code here:
        main.mainASYS.setVisible(false);
        
        main.metodoTransporte = new MetodoTransporte(this.main);
        main.metodoTransporte.setVisible(true); 
    }//GEN-LAST:event_MetodoTransporteMouseClicked

    private void TeoriaInventariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeoriaInventariosMouseClicked
        // TODO add your handling code here:
        main.mainASYS.setVisible(false);
        
        main.teoriaInventarios = new TeoriaInventarios(this.main);
        main.teoriaInventarios.setVisible(true);
    }//GEN-LAST:event_TeoriaInventariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainASYS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainASYS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainASYS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainASYS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainASYS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MetodoTransporte;
    private javax.swing.JLabel ProgramacionLineal;
    private javax.swing.JLabel TeoriaInventarios;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bgLogo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbASYSC;
    private javax.swing.JLabel lblFoot;
    private javax.swing.JLabel lblFoot1;
    private javax.swing.JLabel lblTema1;
    private javax.swing.JLabel lblTema2;
    private javax.swing.JLabel lblTema3;
    private javax.swing.JLabel logoTecNM;
    // End of variables declaration//GEN-END:variables
}
