
package gui;

import java.awt.Color;
import app.Main;
/**
 *
 * @author xeon
 */
public class ProgramacionLineal extends javax.swing.JFrame {
    Main main;
    /**
     * Creates new form ComplexNumberASYS
     */
    public ProgramacionLineal(Main main) {
        initComponents();
        
        this.main = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdd = new javax.swing.JLabel();
        lblSubs = new javax.swing.JLabel();
        lblMult = new javax.swing.JLabel();
        lblDiv = new javax.swing.JLabel();
        lblModZ1 = new javax.swing.JLabel();
        lblArgZ1 = new javax.swing.JLabel();
        tfZ1Real = new javax.swing.JTextField();
        lblReal = new javax.swing.JLabel();
        tfZ2Real = new javax.swing.JTextField();
        tfZ1Imag = new javax.swing.JTextField();
        tfZ2Imag = new javax.swing.JTextField();
        lbImag = new javax.swing.JLabel();
        btnCompute = new javax.swing.JButton();
        pnlComplexNumbers = new javax.swing.JPanel();
        lblHOME = new javax.swing.JLabel();
        lblComplexNumbers = new javax.swing.JLabel();
        lblLogoComplexNumbers = new javax.swing.JLabel();
        lblTema1 = new javax.swing.JLabel();
        lblIndicacion = new javax.swing.JLabel();
        lblZ1 = new javax.swing.JLabel();
        lblZ2 = new javax.swing.JLabel();
        lblFoot = new javax.swing.JLabel();
        lblFoot1 = new javax.swing.JLabel();

        lblAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAdd.setForeground(new java.awt.Color(255, 255, 255));
        lblAdd.setText("Z1 + Z2: ");

        lblSubs.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSubs.setForeground(new java.awt.Color(255, 255, 255));
        lblSubs.setText("Z1   - Z2: ");

        lblMult.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMult.setForeground(new java.awt.Color(255, 255, 255));
        lblMult.setText("Z1  *  Z2: ");

        lblDiv.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDiv.setForeground(new java.awt.Color(255, 255, 255));
        lblDiv.setText("Z1  /  Z2:");

        lblModZ1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblModZ1.setForeground(new java.awt.Color(255, 255, 255));
        lblModZ1.setText("     | Z1 |:");

        lblArgZ1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblArgZ1.setForeground(new java.awt.Color(255, 255, 255));
        lblArgZ1.setText("Arg(Z1):");

        tfZ1Real.setText("1.0");
        tfZ1Real.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfZ1RealActionPerformed(evt);
            }
        });

        lblReal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblReal.setForeground(new java.awt.Color(255, 255, 255));
        lblReal.setText("Real");

        tfZ2Real.setText("1.0");
        tfZ2Real.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfZ2RealActionPerformed(evt);
            }
        });

        tfZ1Imag.setText("1.0");

        tfZ2Imag.setText("1.0");
        tfZ2Imag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfZ2ImagActionPerformed(evt);
            }
        });

        lbImag.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbImag.setForeground(new java.awt.Color(255, 255, 255));
        lbImag.setText("Imag");

        btnCompute.setText("Compute");
        btnCompute.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlComplexNumbers.setBackground(new java.awt.Color(0, 0, 0));
        pnlComplexNumbers.setForeground(new java.awt.Color(0, 255, 204));
        pnlComplexNumbers.setPreferredSize(new java.awt.Dimension(800, 500));
        pnlComplexNumbers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHOME.setBackground(new java.awt.Color(0, 0, 0));
        lblHOME.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lblHOME.setForeground(new java.awt.Color(51, 255, 204));
        lblHOME.setText("Inicio");
        lblHOME.setOpaque(true);
        lblHOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHOMEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHOMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHOMEMouseExited(evt);
            }
        });
        pnlComplexNumbers.add(lblHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 70, 50));

        lblComplexNumbers.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        lblComplexNumbers.setForeground(new java.awt.Color(51, 153, 255));
        lblComplexNumbers.setText("Programacion Lineal");
        pnlComplexNumbers.add(lblComplexNumbers, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 430, 50));

        lblLogoComplexNumbers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coorr black.png"))); // NOI18N
        lblLogoComplexNumbers.setText("jLabel1");
        pnlComplexNumbers.add(lblLogoComplexNumbers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 120));

        lblTema1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTema1.setForeground(new java.awt.Color(255, 255, 255));
        lblTema1.setText("Tema 1. Aplica el metodo grafico y Simplex para resolver los siguientes");
        pnlComplexNumbers.add(lblTema1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 590, 30));

        lblIndicacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIndicacion.setForeground(new java.awt.Color(255, 255, 255));
        lblIndicacion.setText("Indicaciones: Maximiza las utilidades de una granja de 45 acres que cosecha  trigo y maiz");
        pnlComplexNumbers.add(lblIndicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 570, 20));

        lblZ1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblZ1.setForeground(new java.awt.Color(255, 255, 255));
        lblZ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/prog L.png"))); // NOI18N
        lblZ1.setText("Número complejo Z1: ");
        pnlComplexNumbers.add(lblZ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 310, 410));

        lblZ2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblZ2.setForeground(new java.awt.Color(255, 255, 255));
        pnlComplexNumbers.add(lblZ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        lblFoot.setForeground(new java.awt.Color(51, 153, 255));
        lblFoot.setText("ERICK FLORES TAPIA");
        pnlComplexNumbers.add(lblFoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, -1, -1));

        lblFoot1.setForeground(new java.awt.Color(51, 153, 255));
        lblFoot1.setText("ITESS-TICS-2023 Ago-Dic");
        pnlComplexNumbers.add(lblFoot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlComplexNumbers, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlComplexNumbers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblHOMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHOMEMouseEntered
        // TODO add your handling code here:
        lblHOME.setBackground(Color.yellow);
    }//GEN-LAST:event_lblHOMEMouseEntered

    private void lblHOMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHOMEMouseExited
        // TODO add your handling code here:
        lblHOME.setBackground(Color.black);
    }//GEN-LAST:event_lblHOMEMouseExited

    private void lblHOMEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHOMEMouseClicked
       // TODO add your handling code here:
       main.programacionLineal.setVisible(false);
       main.programacionLineal = null;
       
       main.mainASYS.setVisible(true);
    }//GEN-LAST:event_lblHOMEMouseClicked

    private void tfZ1RealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfZ1RealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfZ1RealActionPerformed

    private void tfZ2ImagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfZ2ImagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfZ2ImagActionPerformed

    private void tfZ2RealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfZ2RealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfZ2RealActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramacionLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramacionLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramacionLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramacionLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ComplexNumbersASYS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompute;
    private javax.swing.JLabel lbImag;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblArgZ1;
    private javax.swing.JLabel lblComplexNumbers;
    private javax.swing.JLabel lblDiv;
    private javax.swing.JLabel lblFoot;
    private javax.swing.JLabel lblFoot1;
    private javax.swing.JLabel lblHOME;
    private javax.swing.JLabel lblIndicacion;
    private javax.swing.JLabel lblLogoComplexNumbers;
    private javax.swing.JLabel lblModZ1;
    private javax.swing.JLabel lblMult;
    private javax.swing.JLabel lblReal;
    private javax.swing.JLabel lblSubs;
    private javax.swing.JLabel lblTema1;
    private javax.swing.JLabel lblZ1;
    private javax.swing.JLabel lblZ2;
    private javax.swing.JPanel pnlComplexNumbers;
    private javax.swing.JTextField tfZ1Imag;
    private javax.swing.JTextField tfZ1Real;
    private javax.swing.JTextField tfZ2Imag;
    private javax.swing.JTextField tfZ2Real;
    // End of variables declaration//GEN-END:variables
}
